services:
  postgres:
    image: 'postgres:16.4-bullseye'
    ports:
      - 15432:5432
    env_file:
      - ../.docker-env
    volumes:
      - data:/var/lib/postgresql/data/
    restart: unless-stopped


  pgadmin:
    image: dpage/pgadmin4:latest
    env_file:
      - ../.docker-env  
    ports:
      - 12008:80
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  data:
    

