services:
  postgres:
    image: 'postgres:16.4-bullseye'
    ports:
      - 13001:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - data:/var/lib/postgresql/data/
    restart: unless-stopped


  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 13002:80
    depends_on:
      - postgres
    restart: unless-stopped

  prefect-server:
    image: prefecthq/prefect:3.0.11-python3.12
    environment:
      - PREFECT_SERVER_API_HOST=0.0.0.0
      - PREFECT_API_URL=http://127.0.0.1:13003/api
      - PREFECT_UI_URL=http://127.0.0.1:13003/api
    ports:
      - 13003:4200
    volumes:
      - prefect_server:/root/.prefect
    entrypoint: ["/opt/prefect/entrypoint.sh", "prefect", "server", "start"]

    restart: unless-stopped

  prefect-agent:
    container_name: athlon_prefect_agent
    image: index.docker.io/auckebos/athlon-flex-notifier:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - ATHLON_USERNAME=${ATHLON_USERNAME}
      - ATHLON_PASSWORD=${ATHLON_PASSWORD}
      - GROSS_YEARLY_INCOME=${GROSS_YEARLY_INCOME}
      - APPLY_LOONHEFFINGSKORTING=${APPLY_LOONHEFFINGSKORTING}
      - EMAIL_FROM=${EMAIL_FROM}
      - EMAIL_TO=${EMAIL_TO}
      - GOOGLE_APP_PASSWORD=${GOOGLE_APP_PASSWORD}
      - PREFECT_API_URL=${PREFECT_API_URL}
    ports:
      - "13004:8787"    
    depends_on:
      - prefect-server
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300 athlon_prefect_agent
    restart: unless-stopped    

volumes:
  data:
  prefect_server:
    

